
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.21.0
 */

package com.example.services;

import javax.annotation.Nonnull;
import javax.inject.Named;
import com.example.namespaces.odata06.BSEGByKeyFluentHelper;
import com.example.namespaces.odata06.BSEGFluentHelper;
import com.example.namespaces.odata06.BSEG_tempByKeyFluentHelper;
import com.example.namespaces.odata06.BSEG_tempFluentHelper;
import com.example.namespaces.odata06.DummyHeaderByKeyFluentHelper;
import com.example.namespaces.odata06.batch.DefaultOdata06ServiceBatch;


/**
 * <h3>Details:</h3><table summary='Details'><tr><td align='right'>OData Service:</td><td>Odata06</td></tr></table>
 * 
 */
@Named("com.example.services.DefaultOdata06Service")
public class DefaultOdata06Service
    implements Odata06Service
{

    @Nonnull
    private final String servicePath;

    /**
     * Creates a service using {@link Odata06Service#DEFAULT_SERVICE_PATH} to send the requests.
     * 
     */
    public DefaultOdata06Service() {
        servicePath = Odata06Service.DEFAULT_SERVICE_PATH;
    }

    /**
     * Creates a service using the provided service path to send the requests.
     * <p>
     * Used by the fluent {@link #withServicePath(String)} method.
     * 
     */
    private DefaultOdata06Service(
        @Nonnull
        final String servicePath) {
        this.servicePath = servicePath;
    }

    @Override
    @Nonnull
    public DefaultOdata06Service withServicePath(
        @Nonnull
        final String servicePath) {
        return new DefaultOdata06Service(servicePath);
    }

    /**
     * {@inheritDoc}
     * 
     */
    @Override
    @Nonnull
    public DefaultOdata06ServiceBatch batch() {
        return new DefaultOdata06ServiceBatch(this);
    }

    @Override
    @Nonnull
    public BSEGFluentHelper getAllBSEG() {
        return new BSEGFluentHelper(servicePath);
    }

    @Override
    @Nonnull
    public BSEGByKeyFluentHelper getBSEGByKey(final String bukrs, final String belnr, final String gjahr, final String buzei) {
        return new BSEGByKeyFluentHelper(servicePath, bukrs, belnr, gjahr, buzei);
    }

    @Override
    @Nonnull
    public DummyHeaderByKeyFluentHelper getDummyHeaderByKey(final String dummyKey) {
        return new DummyHeaderByKeyFluentHelper(servicePath, dummyKey);
    }

    @Override
    @Nonnull
    public BSEG_tempFluentHelper getAllBSEG_temp() {
        return new BSEG_tempFluentHelper(servicePath);
    }

    @Override
    @Nonnull
    public BSEG_tempByKeyFluentHelper getBSEG_tempByKey(final String bukrs, final String belnr, final String gjahr, final String buzei) {
        return new BSEG_tempByKeyFluentHelper(servicePath, bukrs, belnr, gjahr, buzei);
    }

}
