
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.21.0
 */

package com.example.services;

import javax.annotation.Nonnull;
import com.example.namespaces.odata06.BSEGByKeyFluentHelper;
import com.example.namespaces.odata06.BSEGFluentHelper;
import com.example.namespaces.odata06.BSEG_tempByKeyFluentHelper;
import com.example.namespaces.odata06.BSEG_tempFluentHelper;
import com.example.namespaces.odata06.DummyHeaderByKeyFluentHelper;
import com.example.namespaces.odata06.batch.Odata06ServiceBatch;
import com.sap.cloud.sdk.datamodel.odata.helper.batch.BatchService;


/**
 * <h3>Details:</h3><table summary='Details'><tr><td align='right'>OData Service:</td><td>Odata06</td></tr></table>
 * 
 */
public interface Odata06Service
    extends BatchService<Odata06ServiceBatch>
{

    /**
     * If no other path was provided via the {@link #withServicePath(String)} method, this is the default service path used to access the endpoint.
     * 
     */
    String DEFAULT_SERVICE_PATH = "/sap/opu/odata/sap/Y_ODATA_SZ_06_SRV";

    /**
     * Overrides the default service path and returns a new service instance with the specified service path. Also adjusts the respective entity URLs.
     * 
     * @param servicePath
     *     Service path that will override the default.
     * @return
     *     A new service instance with the specified service path.
     */
    @Nonnull
    Odata06Service withServicePath(
        @Nonnull
        final String servicePath);

    /**
     * Fetch multiple {@link com.example.namespaces.odata06.BSEG BSEG} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link com.example.namespaces.odata06.BSEG BSEG} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.example.namespaces.odata06.BSEGFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    BSEGFluentHelper getAllBSEG();

    /**
     * Fetch a single {@link com.example.namespaces.odata06.BSEG BSEG} entity using key fields.
     * 
     * @param bukrs
     *     Bukrs<p>Constraints: Not nullable, Maximum length: 4</p>
     * @param gjahr
     *     Gjahr<p>Constraints: Not nullable, Maximum length: 4</p>
     * @param buzei
     *     Buzei<p>Constraints: Not nullable, Maximum length: 3</p>
     * @param belnr
     *     Belnr<p>Constraints: Not nullable, Maximum length: 10</p>
     * @return
     *     A fluent helper to fetch a single {@link com.example.namespaces.odata06.BSEG BSEG} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.example.namespaces.odata06.BSEGByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    BSEGByKeyFluentHelper getBSEGByKey(final String bukrs, final String belnr, final String gjahr, final String buzei);

    /**
     * Fetch a single {@link com.example.namespaces.odata06.DummyHeader DummyHeader} entity using key fields.
     * 
     * @param dummyKey
     *     
     * @return
     *     A fluent helper to fetch a single {@link com.example.namespaces.odata06.DummyHeader DummyHeader} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.example.namespaces.odata06.DummyHeaderByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    DummyHeaderByKeyFluentHelper getDummyHeaderByKey(final String dummyKey);

    /**
     * Fetch multiple {@link com.example.namespaces.odata06.BSEG_temp BSEG_temp} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link com.example.namespaces.odata06.BSEG_temp BSEG_temp} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.example.namespaces.odata06.BSEG_tempFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    BSEG_tempFluentHelper getAllBSEG_temp();

    /**
     * Fetch a single {@link com.example.namespaces.odata06.BSEG_temp BSEG_temp} entity using key fields.
     * 
     * @param bukrs
     *     Bukrs<p>Constraints: Not nullable, Maximum length: 4</p>
     * @param gjahr
     *     Gjahr<p>Constraints: Not nullable, Maximum length: 4</p>
     * @param buzei
     *     Buzei<p>Constraints: Not nullable, Maximum length: 3</p>
     * @param belnr
     *     Belnr<p>Constraints: Not nullable, Maximum length: 10</p>
     * @return
     *     A fluent helper to fetch a single {@link com.example.namespaces.odata06.BSEG_temp BSEG_temp} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.example.namespaces.odata06.BSEG_tempByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    BSEG_tempByKeyFluentHelper getBSEG_tempByKey(final String bukrs, final String belnr, final String gjahr, final String buzei);

}
