
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.21.0
 */

package com.example.namespaces.odata06.link;

import javax.annotation.Nonnull;
import com.example.namespaces.odata06.BSEG;
import com.example.namespaces.odata06.selectable.BSEGSelectable;
import com.sap.cloud.sdk.datamodel.odata.helper.EntityLink;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmObject;


/**
 * Template class to represent entity navigation links of {@link com.example.namespaces.odata06.BSEG BSEG} to other entities. Instances of this object are used in query modifier methods of the entity
 * fluent helpers. Contains methods to compare a field's value with a provided value.
 * 
 * Use the constants declared in each entity inner class. Instantiating directly requires knowing the underlying OData
 * field names, so use the constructor with caution.
 * 
 * @param <ObjectT>
 * Entity type of subclasses from {@link com.sap.cloud.sdk.datamodel.odata.helper.VdmObject VdmObject}.
 * 
 */
public class BSEGLink<ObjectT extends VdmObject<?> >
    extends EntityLink<BSEGLink<ObjectT> , BSEG, ObjectT>
    implements BSEGSelectable
{


    /**
     * Use the constants declared in each entity inner class. Instantiating directly requires knowing the underlying OData field names, so use with caution.
     * 
     * @param fieldName
     *     OData navigation field name. Must match the field returned by the underlying OData service.
     */
    public BSEGLink(final String fieldName) {
        super(fieldName);
    }

    private BSEGLink(final EntityLink<BSEGLink<ObjectT> , BSEG, ObjectT> toClone) {
        super(toClone);
    }

    @Nonnull
    @Override
    protected BSEGLink<ObjectT> translateLinkType(final EntityLink<BSEGLink<ObjectT> , BSEG, ObjectT> link) {
        return new BSEGLink<ObjectT>(link);
    }

}
