
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.21.0
 */

package com.example.namespaces.odata06.link;

import javax.annotation.Nonnull;
import com.example.namespaces.odata06.DummyHeader;
import com.example.namespaces.odata06.selectable.DummyHeaderSelectable;
import com.sap.cloud.sdk.datamodel.odata.helper.EntityLink;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmObject;


/**
 * Template class to represent entity navigation links of {@link com.example.namespaces.odata06.DummyHeader DummyHeader} to other entities. Instances of this object are used in query modifier methods of the entity
 * fluent helpers. Contains methods to compare a field's value with a provided value.
 * 
 * Use the constants declared in each entity inner class. Instantiating directly requires knowing the underlying OData
 * field names, so use the constructor with caution.
 * 
 * @param <ObjectT>
 * Entity type of subclasses from {@link com.sap.cloud.sdk.datamodel.odata.helper.VdmObject VdmObject}.
 * 
 */
public class DummyHeaderLink<ObjectT extends VdmObject<?> >
    extends EntityLink<DummyHeaderLink<ObjectT> , DummyHeader, ObjectT>
    implements DummyHeaderSelectable
{


    /**
     * Use the constants declared in each entity inner class. Instantiating directly requires knowing the underlying OData field names, so use with caution.
     * 
     * @param fieldName
     *     OData navigation field name. Must match the field returned by the underlying OData service.
     */
    public DummyHeaderLink(final String fieldName) {
        super(fieldName);
    }

    private DummyHeaderLink(final EntityLink<DummyHeaderLink<ObjectT> , DummyHeader, ObjectT> toClone) {
        super(toClone);
    }

    @Nonnull
    @Override
    protected DummyHeaderLink<ObjectT> translateLinkType(final EntityLink<DummyHeaderLink<ObjectT> , DummyHeader, ObjectT> link) {
        return new DummyHeaderLink<ObjectT>(link);
    }

}
