
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.21.0
 */

package com.example.namespaces.odata06;

import java.util.Collections;
import java.util.List;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.example.namespaces.odata06.field.BSEGField;
import com.example.namespaces.odata06.selectable.BSEGSelectable;
import com.example.services.Odata06Service;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.cloudplatform.connectivity.HttpDestinationProperties;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmEntity;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import com.sap.cloud.sdk.s4hana.datamodel.odata.annotation.Key;
import com.sap.cloud.sdk.typeconverter.TypeConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original entity name from the Odata EDM: <b>BSEG</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class BSEG
    extends VdmEntity<BSEG>
{

    /**
     * Selector for all available fields of BSEG.
     * 
     */
    public final static BSEGSelectable ALL_FIELDS = new BSEGSelectable() {


        @Nonnull
        @Override
        public String getFieldName() {
            return "*";
        }

        @Nonnull
        @Override
        public List<String> getSelections() {
            return Collections.singletonList("*");
        }

    }
    ;
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>Bukrs</b></p>
     * 
     * @return
     *     Bukrs
     */
    @Key
    @SerializedName("Bukrs")
    @JsonProperty("Bukrs")
    @Nullable
    @ODataField(odataName = "Bukrs")
    private String bukrs;
    /**
     * Use with available fluent helpers to apply the <b>Bukrs</b> field to query operations.
     * 
     */
    public final static BSEGField<String> BUKRS = new BSEGField<String>("Bukrs");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Belnr</b></p>
     * 
     * @return
     *     Belnr
     */
    @Key
    @SerializedName("Belnr")
    @JsonProperty("Belnr")
    @Nullable
    @ODataField(odataName = "Belnr")
    private String belnr;
    /**
     * Use with available fluent helpers to apply the <b>Belnr</b> field to query operations.
     * 
     */
    public final static BSEGField<String> BELNR = new BSEGField<String>("Belnr");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>Gjahr</b></p>
     * 
     * @return
     *     Gjahr
     */
    @Key
    @SerializedName("Gjahr")
    @JsonProperty("Gjahr")
    @Nullable
    @ODataField(odataName = "Gjahr")
    private String gjahr;
    /**
     * Use with available fluent helpers to apply the <b>Gjahr</b> field to query operations.
     * 
     */
    public final static BSEGField<String> GJAHR = new BSEGField<String>("Gjahr");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>Buzei</b></p>
     * 
     * @return
     *     Buzei
     */
    @Key
    @SerializedName("Buzei")
    @JsonProperty("Buzei")
    @Nullable
    @ODataField(odataName = "Buzei")
    private String buzei;
    /**
     * Use with available fluent helpers to apply the <b>Buzei</b> field to query operations.
     * 
     */
    public final static BSEGField<String> BUZEI = new BSEGField<String>("Buzei");
    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>Bschl</b></p>
     * 
     * @return
     *     Bschl
     */
    @SerializedName("Bschl")
    @JsonProperty("Bschl")
    @Nullable
    @ODataField(odataName = "Bschl")
    private String bschl;
    /**
     * Use with available fluent helpers to apply the <b>Bschl</b> field to query operations.
     * 
     */
    public final static BSEGField<String> BSCHL = new BSEGField<String>("Bschl");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>Koart</b></p>
     * 
     * @return
     *     Koart
     */
    @SerializedName("Koart")
    @JsonProperty("Koart")
    @Nullable
    @ODataField(odataName = "Koart")
    private String koart;
    /**
     * Use with available fluent helpers to apply the <b>Koart</b> field to query operations.
     * 
     */
    public final static BSEGField<String> KOART = new BSEGField<String>("Koart");

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public Class<BSEG> getType() {
        return BSEG.class;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>Bukrs</b></p>
     * 
     * @param bukrs
     *     Bukrs
     */
    public void setBukrs(
        @Nullable
        final String bukrs) {
        rememberChangedField("Bukrs", this.bukrs);
        this.bukrs = bukrs;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Belnr</b></p>
     * 
     * @param belnr
     *     Belnr
     */
    public void setBelnr(
        @Nullable
        final String belnr) {
        rememberChangedField("Belnr", this.belnr);
        this.belnr = belnr;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>Gjahr</b></p>
     * 
     * @param gjahr
     *     Gjahr
     */
    public void setGjahr(
        @Nullable
        final String gjahr) {
        rememberChangedField("Gjahr", this.gjahr);
        this.gjahr = gjahr;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>Buzei</b></p>
     * 
     * @param buzei
     *     Buzei
     */
    public void setBuzei(
        @Nullable
        final String buzei) {
        rememberChangedField("Buzei", this.buzei);
        this.buzei = buzei;
    }

    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>Bschl</b></p>
     * 
     * @param bschl
     *     Bschl
     */
    public void setBschl(
        @Nullable
        final String bschl) {
        rememberChangedField("Bschl", this.bschl);
        this.bschl = bschl;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>Koart</b></p>
     * 
     * @param koart
     *     Koart
     */
    public void setKoart(
        @Nullable
        final String koart) {
        rememberChangedField("Koart", this.koart);
        this.koart = koart;
    }

    @Override
    protected String getEntityCollection() {
        return "BSEGSet";
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        result.put("Bukrs", getBukrs());
        result.put("Belnr", getBelnr());
        result.put("Gjahr", getGjahr());
        result.put("Buzei", getBuzei());
        return result;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("Bukrs", getBukrs());
        values.put("Belnr", getBelnr());
        values.put("Gjahr", getGjahr());
        values.put("Buzei", getBuzei());
        values.put("Bschl", getBschl());
        values.put("Koart", getKoart());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("Bukrs")) {
                final Object value = values.remove("Bukrs");
                if ((value == null)||(!value.equals(getBukrs()))) {
                    setBukrs(((String) value));
                }
            }
            if (values.containsKey("Belnr")) {
                final Object value = values.remove("Belnr");
                if ((value == null)||(!value.equals(getBelnr()))) {
                    setBelnr(((String) value));
                }
            }
            if (values.containsKey("Gjahr")) {
                final Object value = values.remove("Gjahr");
                if ((value == null)||(!value.equals(getGjahr()))) {
                    setGjahr(((String) value));
                }
            }
            if (values.containsKey("Buzei")) {
                final Object value = values.remove("Buzei");
                if ((value == null)||(!value.equals(getBuzei()))) {
                    setBuzei(((String) value));
                }
            }
            if (values.containsKey("Bschl")) {
                final Object value = values.remove("Bschl");
                if ((value == null)||(!value.equals(getBschl()))) {
                    setBschl(((String) value));
                }
            }
            if (values.containsKey("Koart")) {
                final Object value = values.remove("Koart");
                if ((value == null)||(!value.equals(getKoart()))) {
                    setKoart(((String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param fieldType
     *     The Java type to use for the extension field when performing value comparisons.
     * @return
     *     A representation of an extension field from this entity.
     */
    @Nonnull
    public static<T >BSEGField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final Class<T> fieldType) {
        return new BSEGField<T>(fieldName);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param typeConverter
     *     A TypeConverter<T, DomainT> instance whose first generic type matches the Java type of the field
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param <DomainT>
     *     The type of the extension field as returned by the OData service.
     * @return
     *     A representation of an extension field from this entity, holding a reference to the given TypeConverter.
     */
    @Nonnull
    public static<T,DomainT >BSEGField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final TypeConverter<T, DomainT> typeConverter) {
        return new BSEGField<T>(fieldName, typeConverter);
    }

    @Override
    @Nullable
    public HttpDestinationProperties getDestinationForFetch() {
        return super.getDestinationForFetch();
    }

    @Override
    protected void setServicePathForFetch(
        @Nullable
        final String servicePathForFetch) {
        super.setServicePathForFetch(servicePathForFetch);
    }

    @Override
    public void attachToService(
        @Nullable
        final String servicePath,
        @Nonnull
        final HttpDestinationProperties destination) {
        super.attachToService(servicePath, destination);
    }

    @Override
    protected String getDefaultServicePath() {
        return Odata06Service.DEFAULT_SERVICE_PATH;
    }

}
