
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.21.0
 */

package com.example.namespaces.odata06;

import java.math.BigDecimal;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.example.namespaces.odata06.field.BSEG_tempField;
import com.example.namespaces.odata06.selectable.BSEG_tempSelectable;
import com.example.services.Odata06Service;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.cloudplatform.connectivity.HttpDestinationProperties;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmEntity;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import com.sap.cloud.sdk.s4hana.datamodel.odata.annotation.Key;
import com.sap.cloud.sdk.typeconverter.TypeConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original entity name from the Odata EDM: <b>BSEG_temp</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class BSEG_temp
    extends VdmEntity<BSEG_temp>
{

    /**
     * Selector for all available fields of BSEG_temp.
     * 
     */
    public final static BSEG_tempSelectable ALL_FIELDS = new BSEG_tempSelectable() {


        @Nonnull
        @Override
        public String getFieldName() {
            return "*";
        }

        @Nonnull
        @Override
        public List<String> getSelections() {
            return Collections.singletonList("*");
        }

    }
    ;
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>Bukrs</b></p>
     * 
     * @return
     *     Bukrs
     */
    @Key
    @SerializedName("Bukrs")
    @JsonProperty("Bukrs")
    @Nullable
    @ODataField(odataName = "Bukrs")
    private String bukrs;
    /**
     * Use with available fluent helpers to apply the <b>Bukrs</b> field to query operations.
     * 
     */
    public final static BSEG_tempField<String> BUKRS = new BSEG_tempField<String>("Bukrs");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Belnr</b></p>
     * 
     * @return
     *     Belnr
     */
    @Key
    @SerializedName("Belnr")
    @JsonProperty("Belnr")
    @Nullable
    @ODataField(odataName = "Belnr")
    private String belnr;
    /**
     * Use with available fluent helpers to apply the <b>Belnr</b> field to query operations.
     * 
     */
    public final static BSEG_tempField<String> BELNR = new BSEG_tempField<String>("Belnr");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>Gjahr</b></p>
     * 
     * @return
     *     Gjahr
     */
    @Key
    @SerializedName("Gjahr")
    @JsonProperty("Gjahr")
    @Nullable
    @ODataField(odataName = "Gjahr")
    private String gjahr;
    /**
     * Use with available fluent helpers to apply the <b>Gjahr</b> field to query operations.
     * 
     */
    public final static BSEG_tempField<String> GJAHR = new BSEG_tempField<String>("Gjahr");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>Buzei</b></p>
     * 
     * @return
     *     Buzei
     */
    @Key
    @SerializedName("Buzei")
    @JsonProperty("Buzei")
    @Nullable
    @ODataField(odataName = "Buzei")
    private String buzei;
    /**
     * Use with available fluent helpers to apply the <b>Buzei</b> field to query operations.
     * 
     */
    public final static BSEG_tempField<String> BUZEI = new BSEG_tempField<String>("Buzei");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>Koart</b></p>
     * 
     * @return
     *     Koart
     */
    @SerializedName("Koart")
    @JsonProperty("Koart")
    @Nullable
    @ODataField(odataName = "Koart")
    private String koart;
    /**
     * Use with available fluent helpers to apply the <b>Koart</b> field to query operations.
     * 
     */
    public final static BSEG_tempField<String> KOART = new BSEG_tempField<String>("Koart");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>Shkzg</b></p>
     * 
     * @return
     *     Shkzg
     */
    @SerializedName("Shkzg")
    @JsonProperty("Shkzg")
    @Nullable
    @ODataField(odataName = "Shkzg")
    private String shkzg;
    /**
     * Use with available fluent helpers to apply the <b>Shkzg</b> field to query operations.
     * 
     */
    public final static BSEG_tempField<String> SHKZG = new BSEG_tempField<String>("Shkzg");
    /**
     * Constraints: Not nullable, Precision: 24, Scale: 3 <p>Original property name from the Odata EDM: <b>Dmbtr</b></p>
     * 
     * @return
     *     Dmbtr
     */
    @SerializedName("Dmbtr")
    @JsonProperty("Dmbtr")
    @Nullable
    @ODataField(odataName = "Dmbtr")
    private BigDecimal dmbtr;
    /**
     * Use with available fluent helpers to apply the <b>Dmbtr</b> field to query operations.
     * 
     */
    public final static BSEG_tempField<BigDecimal> DMBTR = new BSEG_tempField<BigDecimal>("Dmbtr");
    /**
     * Constraints: Not nullable, Precision: 24, Scale: 3 <p>Original property name from the Odata EDM: <b>Wrbtr</b></p>
     * 
     * @return
     *     Wrbtr
     */
    @SerializedName("Wrbtr")
    @JsonProperty("Wrbtr")
    @Nullable
    @ODataField(odataName = "Wrbtr")
    private BigDecimal wrbtr;
    /**
     * Use with available fluent helpers to apply the <b>Wrbtr</b> field to query operations.
     * 
     */
    public final static BSEG_tempField<BigDecimal> WRBTR = new BSEG_tempField<BigDecimal>("Wrbtr");
    /**
     * Constraints: Not nullable, Maximum length: 5 <p>Original property name from the Odata EDM: <b>Pswsl</b></p>
     * 
     * @return
     *     Pswsl
     */
    @SerializedName("Pswsl")
    @JsonProperty("Pswsl")
    @Nullable
    @ODataField(odataName = "Pswsl")
    private String pswsl;
    /**
     * Use with available fluent helpers to apply the <b>Pswsl</b> field to query operations.
     * 
     */
    public final static BSEG_tempField<String> PSWSL = new BSEG_tempField<String>("Pswsl");
    /**
     * Constraints: Not nullable, Precision: 24, Scale: 3 <p>Original property name from the Odata EDM: <b>Fdwbt</b></p>
     * 
     * @return
     *     Fdwbt
     */
    @SerializedName("Fdwbt")
    @JsonProperty("Fdwbt")
    @Nullable
    @ODataField(odataName = "Fdwbt")
    private BigDecimal fdwbt;
    /**
     * Use with available fluent helpers to apply the <b>Fdwbt</b> field to query operations.
     * 
     */
    public final static BSEG_tempField<BigDecimal> FDWBT = new BSEG_tempField<BigDecimal>("Fdwbt");
    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Fdtag</b></p>
     * 
     * @return
     *     Fdtag
     */
    @SerializedName("Fdtag")
    @JsonProperty("Fdtag")
    @Nullable
    @ODataField(odataName = "Fdtag")
    private String fdtag;
    /**
     * Use with available fluent helpers to apply the <b>Fdtag</b> field to query operations.
     * 
     */
    public final static BSEG_tempField<String> FDTAG = new BSEG_tempField<String>("Fdtag");
    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>Fkont</b></p>
     * 
     * @return
     *     Fkont
     */
    @SerializedName("Fkont")
    @JsonProperty("Fkont")
    @Nullable
    @ODataField(odataName = "Fkont")
    private String fkont;
    /**
     * Use with available fluent helpers to apply the <b>Fkont</b> field to query operations.
     * 
     */
    public final static BSEG_tempField<String> FKONT = new BSEG_tempField<String>("Fkont");
    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Hkont</b></p>
     * 
     * @return
     *     Hkont
     */
    @SerializedName("Hkont")
    @JsonProperty("Hkont")
    @Nullable
    @ODataField(odataName = "Hkont")
    private String hkont;
    /**
     * Use with available fluent helpers to apply the <b>Hkont</b> field to query operations.
     * 
     */
    public final static BSEG_tempField<String> HKONT = new BSEG_tempField<String>("Hkont");
    /**
     * Constraints: Not nullable, Maximum length: 5 <p>Original property name from the Odata EDM: <b>Awtyp</b></p>
     * 
     * @return
     *     Awtyp
     */
    @SerializedName("Awtyp")
    @JsonProperty("Awtyp")
    @Nullable
    @ODataField(odataName = "Awtyp")
    private String awtyp;
    /**
     * Use with available fluent helpers to apply the <b>Awtyp</b> field to query operations.
     * 
     */
    public final static BSEG_tempField<String> AWTYP = new BSEG_tempField<String>("Awtyp");
    /**
     * Constraints: Not nullable, Maximum length: 20 <p>Original property name from the Odata EDM: <b>Awkey</b></p>
     * 
     * @return
     *     Awkey
     */
    @SerializedName("Awkey")
    @JsonProperty("Awkey")
    @Nullable
    @ODataField(odataName = "Awkey")
    private String awkey;
    /**
     * Use with available fluent helpers to apply the <b>Awkey</b> field to query operations.
     * 
     */
    public final static BSEG_tempField<String> AWKEY = new BSEG_tempField<String>("Awkey");
    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>HBudat</b></p>
     * 
     * @return
     *     HBudat
     */
    @SerializedName("HBudat")
    @JsonProperty("HBudat")
    @Nullable
    @ODataField(odataName = "HBudat")
    private String hBudat;
    /**
     * Use with available fluent helpers to apply the <b>HBudat</b> field to query operations.
     * 
     */
    public final static BSEG_tempField<String> H_BUDAT = new BSEG_tempField<String>("HBudat");
    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>HBldat</b></p>
     * 
     * @return
     *     HBldat
     */
    @SerializedName("HBldat")
    @JsonProperty("HBldat")
    @Nullable
    @ODataField(odataName = "HBldat")
    private String hBldat;
    /**
     * Use with available fluent helpers to apply the <b>HBldat</b> field to query operations.
     * 
     */
    public final static BSEG_tempField<String> H_BLDAT = new BSEG_tempField<String>("HBldat");
    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>HBlart</b></p>
     * 
     * @return
     *     HBlart
     */
    @SerializedName("HBlart")
    @JsonProperty("HBlart")
    @Nullable
    @ODataField(odataName = "HBlart")
    private String hBlart;
    /**
     * Use with available fluent helpers to apply the <b>HBlart</b> field to query operations.
     * 
     */
    public final static BSEG_tempField<String> H_BLART = new BSEG_tempField<String>("HBlart");
    /**
     * Constraints: Not nullable, Maximum length: 5 <p>Original property name from the Odata EDM: <b>HHwaer</b></p>
     * 
     * @return
     *     HHwaer
     */
    @SerializedName("HHwaer")
    @JsonProperty("HHwaer")
    @Nullable
    @ODataField(odataName = "HHwaer")
    private String hHwaer;
    /**
     * Use with available fluent helpers to apply the <b>HHwaer</b> field to query operations.
     * 
     */
    public final static BSEG_tempField<String> H_HWAER = new BSEG_tempField<String>("HHwaer");

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public Class<BSEG_temp> getType() {
        return BSEG_temp.class;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>Bukrs</b></p>
     * 
     * @param bukrs
     *     Bukrs
     */
    public void setBukrs(
        @Nullable
        final String bukrs) {
        rememberChangedField("Bukrs", this.bukrs);
        this.bukrs = bukrs;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Belnr</b></p>
     * 
     * @param belnr
     *     Belnr
     */
    public void setBelnr(
        @Nullable
        final String belnr) {
        rememberChangedField("Belnr", this.belnr);
        this.belnr = belnr;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>Gjahr</b></p>
     * 
     * @param gjahr
     *     Gjahr
     */
    public void setGjahr(
        @Nullable
        final String gjahr) {
        rememberChangedField("Gjahr", this.gjahr);
        this.gjahr = gjahr;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>Buzei</b></p>
     * 
     * @param buzei
     *     Buzei
     */
    public void setBuzei(
        @Nullable
        final String buzei) {
        rememberChangedField("Buzei", this.buzei);
        this.buzei = buzei;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>Koart</b></p>
     * 
     * @param koart
     *     Koart
     */
    public void setKoart(
        @Nullable
        final String koart) {
        rememberChangedField("Koart", this.koart);
        this.koart = koart;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>Shkzg</b></p>
     * 
     * @param shkzg
     *     Shkzg
     */
    public void setShkzg(
        @Nullable
        final String shkzg) {
        rememberChangedField("Shkzg", this.shkzg);
        this.shkzg = shkzg;
    }

    /**
     * Constraints: Not nullable, Precision: 24, Scale: 3 <p>Original property name from the Odata EDM: <b>Dmbtr</b></p>
     * 
     * @param dmbtr
     *     Dmbtr
     */
    public void setDmbtr(
        @Nullable
        final BigDecimal dmbtr) {
        rememberChangedField("Dmbtr", this.dmbtr);
        this.dmbtr = dmbtr;
    }

    /**
     * Constraints: Not nullable, Precision: 24, Scale: 3 <p>Original property name from the Odata EDM: <b>Wrbtr</b></p>
     * 
     * @param wrbtr
     *     Wrbtr
     */
    public void setWrbtr(
        @Nullable
        final BigDecimal wrbtr) {
        rememberChangedField("Wrbtr", this.wrbtr);
        this.wrbtr = wrbtr;
    }

    /**
     * Constraints: Not nullable, Maximum length: 5 <p>Original property name from the Odata EDM: <b>Pswsl</b></p>
     * 
     * @param pswsl
     *     Pswsl
     */
    public void setPswsl(
        @Nullable
        final String pswsl) {
        rememberChangedField("Pswsl", this.pswsl);
        this.pswsl = pswsl;
    }

    /**
     * Constraints: Not nullable, Precision: 24, Scale: 3 <p>Original property name from the Odata EDM: <b>Fdwbt</b></p>
     * 
     * @param fdwbt
     *     Fdwbt
     */
    public void setFdwbt(
        @Nullable
        final BigDecimal fdwbt) {
        rememberChangedField("Fdwbt", this.fdwbt);
        this.fdwbt = fdwbt;
    }

    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Fdtag</b></p>
     * 
     * @param fdtag
     *     Fdtag
     */
    public void setFdtag(
        @Nullable
        final String fdtag) {
        rememberChangedField("Fdtag", this.fdtag);
        this.fdtag = fdtag;
    }

    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>Fkont</b></p>
     * 
     * @param fkont
     *     Fkont
     */
    public void setFkont(
        @Nullable
        final String fkont) {
        rememberChangedField("Fkont", this.fkont);
        this.fkont = fkont;
    }

    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Hkont</b></p>
     * 
     * @param hkont
     *     Hkont
     */
    public void setHkont(
        @Nullable
        final String hkont) {
        rememberChangedField("Hkont", this.hkont);
        this.hkont = hkont;
    }

    /**
     * Constraints: Not nullable, Maximum length: 5 <p>Original property name from the Odata EDM: <b>Awtyp</b></p>
     * 
     * @param awtyp
     *     Awtyp
     */
    public void setAwtyp(
        @Nullable
        final String awtyp) {
        rememberChangedField("Awtyp", this.awtyp);
        this.awtyp = awtyp;
    }

    /**
     * Constraints: Not nullable, Maximum length: 20 <p>Original property name from the Odata EDM: <b>Awkey</b></p>
     * 
     * @param awkey
     *     Awkey
     */
    public void setAwkey(
        @Nullable
        final String awkey) {
        rememberChangedField("Awkey", this.awkey);
        this.awkey = awkey;
    }

    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>HBudat</b></p>
     * 
     * @param hBudat
     *     HBudat
     */
    public void setHBudat(
        @Nullable
        final String hBudat) {
        rememberChangedField("HBudat", this.hBudat);
        this.hBudat = hBudat;
    }

    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>HBldat</b></p>
     * 
     * @param hBldat
     *     HBldat
     */
    public void setHBldat(
        @Nullable
        final String hBldat) {
        rememberChangedField("HBldat", this.hBldat);
        this.hBldat = hBldat;
    }

    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>HBlart</b></p>
     * 
     * @param hBlart
     *     HBlart
     */
    public void setHBlart(
        @Nullable
        final String hBlart) {
        rememberChangedField("HBlart", this.hBlart);
        this.hBlart = hBlart;
    }

    /**
     * Constraints: Not nullable, Maximum length: 5 <p>Original property name from the Odata EDM: <b>HHwaer</b></p>
     * 
     * @param hHwaer
     *     HHwaer
     */
    public void setHHwaer(
        @Nullable
        final String hHwaer) {
        rememberChangedField("HHwaer", this.hHwaer);
        this.hHwaer = hHwaer;
    }

    @Override
    protected String getEntityCollection() {
        return "BSEG_tempSet";
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        result.put("Bukrs", getBukrs());
        result.put("Belnr", getBelnr());
        result.put("Gjahr", getGjahr());
        result.put("Buzei", getBuzei());
        return result;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("Bukrs", getBukrs());
        values.put("Belnr", getBelnr());
        values.put("Gjahr", getGjahr());
        values.put("Buzei", getBuzei());
        values.put("Koart", getKoart());
        values.put("Shkzg", getShkzg());
        values.put("Dmbtr", getDmbtr());
        values.put("Wrbtr", getWrbtr());
        values.put("Pswsl", getPswsl());
        values.put("Fdwbt", getFdwbt());
        values.put("Fdtag", getFdtag());
        values.put("Fkont", getFkont());
        values.put("Hkont", getHkont());
        values.put("Awtyp", getAwtyp());
        values.put("Awkey", getAwkey());
        values.put("HBudat", getHBudat());
        values.put("HBldat", getHBldat());
        values.put("HBlart", getHBlart());
        values.put("HHwaer", getHHwaer());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("Bukrs")) {
                final Object value = values.remove("Bukrs");
                if ((value == null)||(!value.equals(getBukrs()))) {
                    setBukrs(((String) value));
                }
            }
            if (values.containsKey("Belnr")) {
                final Object value = values.remove("Belnr");
                if ((value == null)||(!value.equals(getBelnr()))) {
                    setBelnr(((String) value));
                }
            }
            if (values.containsKey("Gjahr")) {
                final Object value = values.remove("Gjahr");
                if ((value == null)||(!value.equals(getGjahr()))) {
                    setGjahr(((String) value));
                }
            }
            if (values.containsKey("Buzei")) {
                final Object value = values.remove("Buzei");
                if ((value == null)||(!value.equals(getBuzei()))) {
                    setBuzei(((String) value));
                }
            }
            if (values.containsKey("Koart")) {
                final Object value = values.remove("Koart");
                if ((value == null)||(!value.equals(getKoart()))) {
                    setKoart(((String) value));
                }
            }
            if (values.containsKey("Shkzg")) {
                final Object value = values.remove("Shkzg");
                if ((value == null)||(!value.equals(getShkzg()))) {
                    setShkzg(((String) value));
                }
            }
            if (values.containsKey("Dmbtr")) {
                final Object value = values.remove("Dmbtr");
                if ((value == null)||(!value.equals(getDmbtr()))) {
                    setDmbtr(((BigDecimal) value));
                }
            }
            if (values.containsKey("Wrbtr")) {
                final Object value = values.remove("Wrbtr");
                if ((value == null)||(!value.equals(getWrbtr()))) {
                    setWrbtr(((BigDecimal) value));
                }
            }
            if (values.containsKey("Pswsl")) {
                final Object value = values.remove("Pswsl");
                if ((value == null)||(!value.equals(getPswsl()))) {
                    setPswsl(((String) value));
                }
            }
            if (values.containsKey("Fdwbt")) {
                final Object value = values.remove("Fdwbt");
                if ((value == null)||(!value.equals(getFdwbt()))) {
                    setFdwbt(((BigDecimal) value));
                }
            }
            if (values.containsKey("Fdtag")) {
                final Object value = values.remove("Fdtag");
                if ((value == null)||(!value.equals(getFdtag()))) {
                    setFdtag(((String) value));
                }
            }
            if (values.containsKey("Fkont")) {
                final Object value = values.remove("Fkont");
                if ((value == null)||(!value.equals(getFkont()))) {
                    setFkont(((String) value));
                }
            }
            if (values.containsKey("Hkont")) {
                final Object value = values.remove("Hkont");
                if ((value == null)||(!value.equals(getHkont()))) {
                    setHkont(((String) value));
                }
            }
            if (values.containsKey("Awtyp")) {
                final Object value = values.remove("Awtyp");
                if ((value == null)||(!value.equals(getAwtyp()))) {
                    setAwtyp(((String) value));
                }
            }
            if (values.containsKey("Awkey")) {
                final Object value = values.remove("Awkey");
                if ((value == null)||(!value.equals(getAwkey()))) {
                    setAwkey(((String) value));
                }
            }
            if (values.containsKey("HBudat")) {
                final Object value = values.remove("HBudat");
                if ((value == null)||(!value.equals(getHBudat()))) {
                    setHBudat(((String) value));
                }
            }
            if (values.containsKey("HBldat")) {
                final Object value = values.remove("HBldat");
                if ((value == null)||(!value.equals(getHBldat()))) {
                    setHBldat(((String) value));
                }
            }
            if (values.containsKey("HBlart")) {
                final Object value = values.remove("HBlart");
                if ((value == null)||(!value.equals(getHBlart()))) {
                    setHBlart(((String) value));
                }
            }
            if (values.containsKey("HHwaer")) {
                final Object value = values.remove("HHwaer");
                if ((value == null)||(!value.equals(getHHwaer()))) {
                    setHHwaer(((String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param fieldType
     *     The Java type to use for the extension field when performing value comparisons.
     * @return
     *     A representation of an extension field from this entity.
     */
    @Nonnull
    public static<T >BSEG_tempField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final Class<T> fieldType) {
        return new BSEG_tempField<T>(fieldName);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param typeConverter
     *     A TypeConverter<T, DomainT> instance whose first generic type matches the Java type of the field
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param <DomainT>
     *     The type of the extension field as returned by the OData service.
     * @return
     *     A representation of an extension field from this entity, holding a reference to the given TypeConverter.
     */
    @Nonnull
    public static<T,DomainT >BSEG_tempField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final TypeConverter<T, DomainT> typeConverter) {
        return new BSEG_tempField<T>(fieldName, typeConverter);
    }

    @Override
    @Nullable
    public HttpDestinationProperties getDestinationForFetch() {
        return super.getDestinationForFetch();
    }

    @Override
    protected void setServicePathForFetch(
        @Nullable
        final String servicePathForFetch) {
        super.setServicePathForFetch(servicePathForFetch);
    }

    @Override
    public void attachToService(
        @Nullable
        final String servicePath,
        @Nonnull
        final HttpDestinationProperties destination) {
        super.attachToService(servicePath, destination);
    }

    @Override
    protected String getDefaultServicePath() {
        return Odata06Service.DEFAULT_SERVICE_PATH;
    }

}
