
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.21.0
 */

package com.example.namespaces.odata06;

import javax.annotation.Nonnull;
import com.example.namespaces.odata06.selectable.BSEG_tempSelectable;
import com.sap.cloud.sdk.datamodel.odata.helper.FluentHelperRead;


/**
 * Fluent helper to fetch multiple {@link com.example.namespaces.odata06.BSEG_temp BSEG_temp} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. 
 * 
 */
public class BSEG_tempFluentHelper
    extends FluentHelperRead<BSEG_tempFluentHelper, BSEG_temp, BSEG_tempSelectable>
{


    /**
     * Creates a fluent helper using the specified service path to send the read requests.
     * 
     * @param servicePath
     *     The service path to direct the read requests to.
     */
    public BSEG_tempFluentHelper(
        @Nonnull
        final String servicePath) {
        super(servicePath);
    }

    @Override
    @Nonnull
    protected Class<BSEG_temp> getEntityClass() {
        return BSEG_temp.class;
    }

}
