
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.21.0
 */

package com.example.namespaces.odata06;

import java.util.Collections;
import java.util.List;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.example.namespaces.odata06.field.DummyHeaderField;
import com.example.namespaces.odata06.link.DummyHeaderLink;
import com.example.namespaces.odata06.selectable.DummyHeaderSelectable;
import com.example.services.Odata06Service;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.cloudplatform.connectivity.HttpClientAccessor;
import com.sap.cloud.sdk.cloudplatform.connectivity.HttpDestinationProperties;
import com.sap.cloud.sdk.datamodel.odata.helper.ODataTypeValueSerializer;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmEntity;
import com.sap.cloud.sdk.odatav2.connectivity.ODataException;
import com.sap.cloud.sdk.odatav2.connectivity.ODataExceptionType;
import com.sap.cloud.sdk.odatav2.connectivity.ODataQuery;
import com.sap.cloud.sdk.odatav2.connectivity.ODataQueryBuilder;
import com.sap.cloud.sdk.odatav2.connectivity.ODataQueryResult;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import com.sap.cloud.sdk.s4hana.datamodel.odata.annotation.Key;
import com.sap.cloud.sdk.typeconverter.TypeConverter;
import io.vavr.control.Option;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.apache.http.client.HttpClient;
import org.apache.olingo.odata2.api.edm.EdmSimpleTypeKind;


/**
 * <p>Original entity name from the Odata EDM: <b>DummyHeader</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class DummyHeader
    extends VdmEntity<DummyHeader>
{

    /**
     * Selector for all available fields of DummyHeader.
     * 
     */
    public final static DummyHeaderSelectable ALL_FIELDS = new DummyHeaderSelectable() {


        @Nonnull
        @Override
        public String getFieldName() {
            return "*";
        }

        @Nonnull
        @Override
        public List<String> getSelections() {
            return Collections.singletonList("*");
        }

    }
    ;
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>DummyKey</b></p>
     * 
     * @return
     *     The dummyKey contained in this entity.
     */
    @Key
    @SerializedName("DummyKey")
    @JsonProperty("DummyKey")
    @Nullable
    @ODataField(odataName = "DummyKey")
    private String dummyKey;
    /**
     * Use with available fluent helpers to apply the <b>DummyKey</b> field to query operations.
     * 
     */
    public final static DummyHeaderField<String> DUMMY_KEY = new DummyHeaderField<String>("DummyKey");
    /**
     * Navigation property <b>TBL_BSEG</b> for <b>DummyHeader</b> to multiple <b>BSEG</b>.
     * 
     */
    @SerializedName("TBL_BSEG")
    @JsonProperty("TBL_BSEG")
    @ODataField(odataName = "TBL_BSEG")
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private List<BSEG> toTBL_BSEG;
    /**
     * Use with available fluent helpers to apply the <b>TBL_BSEG</b> navigation property to query operations.
     * 
     */
    public final static DummyHeaderLink<BSEG> TO_TBLBSEG = new DummyHeaderLink<BSEG>("TBL_BSEG");

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public Class<DummyHeader> getType() {
        return DummyHeader.class;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>DummyKey</b></p>
     * 
     * @param dummyKey
     *     The dummyKey to set.
     */
    public void setDummyKey(
        @Nullable
        final String dummyKey) {
        rememberChangedField("DummyKey", this.dummyKey);
        this.dummyKey = dummyKey;
    }

    @Override
    protected String getEntityCollection() {
        return "DummyHeaderSet";
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        result.put("DummyKey", getDummyKey());
        return result;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("DummyKey", getDummyKey());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("DummyKey")) {
                final Object value = values.remove("DummyKey");
                if ((value == null)||(!value.equals(getDummyKey()))) {
                    setDummyKey(((String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
            if ((values).containsKey("TBL_BSEG")) {
                final Object value = (values).remove("TBL_BSEG");
                if (value instanceof Iterable) {
                    if (toTBL_BSEG == null) {
                        toTBL_BSEG = Lists.newArrayList();
                    } else {
                        toTBL_BSEG = Lists.newArrayList(toTBL_BSEG);
                    }
                    int i = 0;
                    for (Object item: ((Iterable<?> ) value)) {
                        if (!(item instanceof Map)) {
                            continue;
                        }
                        BSEG entity;
                        if (toTBL_BSEG.size()>i) {
                            entity = toTBL_BSEG.get(i);
                        } else {
                            entity = new BSEG();
                            toTBL_BSEG.add(entity);
                        }
                        i = (i + 1);
                        @SuppressWarnings("unchecked")
                        final Map<String, Object> inputMap = ((Map<String, Object> ) item);
                        entity.fromMap(inputMap);
                    }
                }
            }
        }
        super.fromMap(values);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param fieldType
     *     The Java type to use for the extension field when performing value comparisons.
     * @return
     *     A representation of an extension field from this entity.
     */
    @Nonnull
    public static<T >DummyHeaderField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final Class<T> fieldType) {
        return new DummyHeaderField<T>(fieldName);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param typeConverter
     *     A TypeConverter<T, DomainT> instance whose first generic type matches the Java type of the field
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param <DomainT>
     *     The type of the extension field as returned by the OData service.
     * @return
     *     A representation of an extension field from this entity, holding a reference to the given TypeConverter.
     */
    @Nonnull
    public static<T,DomainT >DummyHeaderField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final TypeConverter<T, DomainT> typeConverter) {
        return new DummyHeaderField<T>(fieldName, typeConverter);
    }

    @Override
    @Nullable
    public HttpDestinationProperties getDestinationForFetch() {
        return super.getDestinationForFetch();
    }

    @Override
    protected void setServicePathForFetch(
        @Nullable
        final String servicePathForFetch) {
        super.setServicePathForFetch(servicePathForFetch);
    }

    @Override
    public void attachToService(
        @Nullable
        final String servicePath,
        @Nonnull
        final HttpDestinationProperties destination) {
        super.attachToService(servicePath, destination);
    }

    @Override
    protected String getDefaultServicePath() {
        return Odata06Service.DEFAULT_SERVICE_PATH;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfNavigationProperties() {
        final Map<String, Object> values = super.toMapOfNavigationProperties();
        if (toTBL_BSEG!= null) {
            (values).put("TBL_BSEG", toTBL_BSEG);
        }
        return values;
    }

    /**
     * Fetches the <b>BSEG</b> entities (one to many) associated with this entity. This corresponds to the OData navigation property <b>TBL_BSEG</b>.
     * <p>
     * Please note: This method will not cache or persist the query results.
     * 
     * @return
     *     List containing one or more associated <b>BSEG</b> entities. If no entities are associated then an empty list is returned. 
     * @throws ODataException
     *     If the entity is unmanaged, i.e. it has not been retrieved using the OData VDM's services and therefore has no ERP configuration context assigned. An entity is managed if it has been either retrieved using the VDM's services or returned from the VDM's services as the result of a CREATE or UPDATE call. 
     */
    @Nonnull
    public List<BSEG> fetchTBL_BSEG()
        throws ODataException
    {
        final HttpDestinationProperties destination = getDestinationForFetch();
        if (destination == null) {
            throw new ODataException(ODataExceptionType.OTHER, "Failed to fetch related objects of type BSEG.", new IllegalStateException("Unable to execute OData query. The entity was created locally without an assigned HttpDestination. This method is applicable only on entities which were retrieved or created using the OData VDM."));
        }
        final StringBuilder odataResourceUrl = new StringBuilder(getEntityCollection());
        odataResourceUrl.append("(");
        odataResourceUrl.append("DummyKey=");
        odataResourceUrl.append(ODataTypeValueSerializer.of(EdmSimpleTypeKind.String).toUri(dummyKey));
        odataResourceUrl.append(")/");
        odataResourceUrl.append("TBL_BSEG");
        final ODataQueryBuilder builder = ODataQueryBuilder.withEntity(getServicePathForFetch(), odataResourceUrl.toString()).withoutMetadata();
        final ODataQuery query = builder.build();
        final HttpClient httpClient = HttpClientAccessor.getHttpClient(destination);
        final ODataQueryResult result = query.execute(httpClient);
        final List<BSEG> entityList = result.asList(BSEG.class);
        for (BSEG entity: entityList) {
            entity.attachToService(getServicePathForFetch(), destination);
        }
        return entityList;
    }

    /**
     * Retrieval of associated <b>BSEG</b> entities (one to many). This corresponds to the OData navigation property <b>TBL_BSEG</b>.
     * <p>
     * If the navigation property <b>TBL_BSEG</b> of a queried <b>DummyHeader</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @return
     *     List of associated <b>BSEG</b> entities.
     * @throws ODataException
     *     If the entity is unmanaged, i.e. it has not been retrieved using the OData VDM's services and therefore has no ERP configuration context assigned. An entity is managed if it has been either retrieved using the VDM's services or returned from the VDM's services as the result of a CREATE or UPDATE call. 
     */
    @Nonnull
    public List<BSEG> getTBL_BSEGOrFetch()
        throws ODataException
    {
        if (toTBL_BSEG == null) {
            toTBL_BSEG = fetchTBL_BSEG();
        }
        return toTBL_BSEG;
    }

    /**
     * Retrieval of associated <b>BSEG</b> entities (one to many). This corresponds to the OData navigation property <b>TBL_BSEG</b>.
     * <p>
     * If the navigation property for an entity <b>DummyHeader</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>TBL_BSEG</b> is already loaded, the result will contain the <b>BSEG</b> entities. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<List<BSEG>> getTBL_BSEGIfPresent() {
        return Option.of(toTBL_BSEG);
    }

    /**
     * Overwrites the list of associated <b>BSEG</b> entities for the loaded navigation property <b>TBL_BSEG</b>.
     * <p>
     * If the navigation property <b>TBL_BSEG</b> of a queried <b>DummyHeader</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @param value
     *     List of <b>BSEG</b> entities.
     */
    public void setTBL_BSEG(
        @Nonnull
        final List<BSEG> value) {
        if (toTBL_BSEG == null) {
            toTBL_BSEG = Lists.newArrayList();
        }
        toTBL_BSEG.clear();
        toTBL_BSEG.addAll(value);
    }

    /**
     * Adds elements to the list of associated <b>BSEG</b> entities. This corresponds to the OData navigation property <b>TBL_BSEG</b>.
     * <p>
     * If the navigation property <b>TBL_BSEG</b> of a queried <b>DummyHeader</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @param entity
     *     Array of <b>BSEG</b> entities.
     */
    public void addTBL_BSEG(BSEG... entity) {
        if (toTBL_BSEG == null) {
            toTBL_BSEG = Lists.newArrayList();
        }
        toTBL_BSEG.addAll(Lists.newArrayList(entity));
    }


    /**
     * Helper class to allow for fluent creation of DummyHeader instances.
     * 
     */
    public final static class DummyHeaderBuilder {

        private List<BSEG> toTBL_BSEG = Lists.newArrayList();

        private DummyHeader.DummyHeaderBuilder toTBL_BSEG(final List<BSEG> value) {
            toTBL_BSEG.addAll(value);
            return this;
        }

        /**
         * Navigation property <b>TBL_BSEG</b> for <b>DummyHeader</b> to multiple <b>BSEG</b>.
         * 
         * @param value
         *     The BSEGs to build this DummyHeader with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public DummyHeader.DummyHeaderBuilder tbL_BSEG(BSEG... value) {
            return toTBL_BSEG(Lists.newArrayList(value));
        }

    }

}
