
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.21.0
 */

package com.example.namespaces.odata06;

import java.util.Map;
import javax.annotation.Nonnull;
import com.example.namespaces.odata06.selectable.DummyHeaderSelectable;
import com.google.common.collect.Maps;
import com.sap.cloud.sdk.datamodel.odata.helper.FluentHelperByKey;


/**
 * Fluent helper to fetch a single {@link com.example.namespaces.odata06.DummyHeader DummyHeader} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. 
 * 
 */
public class DummyHeaderByKeyFluentHelper
    extends FluentHelperByKey<DummyHeaderByKeyFluentHelper, DummyHeader, DummyHeaderSelectable>
{

    private final Map<String, Object> key = Maps.newHashMap();

    /**
     * Creates a fluent helper object that will fetch a single {@link com.example.namespaces.odata06.DummyHeader DummyHeader} entity with the provided key field values. To perform execution, call the {@link #execute execute} method on the fluent helper object.
     * 
     * @param dummyKey
     *     
     * @param servicePath
     *     Service path to be used to fetch a single {@code DummyHeader}
     */
    public DummyHeaderByKeyFluentHelper(
        @Nonnull
        final String servicePath, final String dummyKey) {
        super(servicePath);
        this.key.put("DummyKey", dummyKey);
    }

    @Override
    @Nonnull
    protected Class<DummyHeader> getEntityClass() {
        return DummyHeader.class;
    }

    @Override
    @Nonnull
    protected Map<String, Object> getKey() {
        return key;
    }

}
