
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.21.0
 */

package com.example.namespaces.odata06.batch;

import javax.annotation.Nonnull;
import com.example.services.Odata06Service;
import com.sap.cloud.sdk.datamodel.odata.helper.batch.BatchFluentHelperBasic;


/**
 * Default implementation of the {@link Odata06ServiceBatch} interface exposed in the {@link com.example.services.Odata06Service Odata06Service}, allowing you to create multiple changesets and finally execute the batch request.
 * 
 */
public class DefaultOdata06ServiceBatch
    extends BatchFluentHelperBasic<Odata06ServiceBatch, Odata06ServiceBatchChangeSet>
    implements Odata06ServiceBatch
{

    @Nonnull
    private final Odata06Service service;

    /**
     * Creates a new instance of this DefaultOdata06ServiceBatch.
     * 
     * @param service
     *     The service to execute all operations in this changeset on.
     */
    public DefaultOdata06ServiceBatch(
        @Nonnull
        final Odata06Service service) {
        this.service = service;
    }

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    protected String getServicePathForBatchRequest() {
        return Odata06Service.DEFAULT_SERVICE_PATH;
    }

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    protected DefaultOdata06ServiceBatch getThis() {
        return this;
    }

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public Odata06ServiceBatchChangeSet beginChangeSet() {
        return new DefaultOdata06ServiceBatchChangeSet(this, service);
    }

}
