
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.21.0
 */

package com.example.namespaces.odata06.batch;

import javax.annotation.Nonnull;
import com.example.services.Odata06Service;
import com.sap.cloud.sdk.datamodel.odata.helper.batch.BatchChangeSetFluentHelperBasic;


/**
 * Implementation of the {@link Odata06ServiceBatchChangeSet} interface, enabling you to combine multiple operations into one changeset. For further information have a look into the {@link com.example.services.Odata06Service Odata06Service}.
 * 
 */
public class DefaultOdata06ServiceBatchChangeSet
    extends BatchChangeSetFluentHelperBasic<Odata06ServiceBatch, Odata06ServiceBatchChangeSet>
    implements Odata06ServiceBatchChangeSet
{

    @Nonnull
    private final Odata06Service service;

    DefaultOdata06ServiceBatchChangeSet(
        @Nonnull
        final DefaultOdata06ServiceBatch batchFluentHelper,
        @Nonnull
        final Odata06Service service) {
        super(batchFluentHelper, batchFluentHelper);
        this.service = service;
    }

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    protected DefaultOdata06ServiceBatchChangeSet getThis() {
        return this;
    }

}
