
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.21.0
 */

package com.example.namespaces.odata06.batch;

import com.sap.cloud.sdk.datamodel.odata.helper.batch.FluentHelperServiceBatch;


/**
 * Interface to the batch object of an {@code com.example.services.Odata06Service Odata06Service} service.
 * 
 */
public interface Odata06ServiceBatch
    extends FluentHelperServiceBatch<Odata06ServiceBatch, Odata06ServiceBatchChangeSet>
{


}
