
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.21.0
 */

package com.example.namespaces.odata06.batch;

import com.sap.cloud.sdk.datamodel.odata.helper.batch.FluentHelperBatchEndChangeSet;


/**
 * This interface enables you to combine multiple operations into one change set. For further information have a look into the {@link com.example.services.Odata06Service Odata06Service}.
 * 
 */
public interface Odata06ServiceBatchChangeSet
    extends FluentHelperBatchEndChangeSet<Odata06ServiceBatch>
{


}
