
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.21.0
 */

package com.example.namespaces.odata06.selectable;

import com.example.namespaces.odata06.BSEG_temp;
import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;


/**
 * Interface to enable OData entity selectors for {@link com.example.namespaces.odata06.BSEG_temp BSEG_temp}. This interface is used by {@link com.example.namespaces.odata06.field.BSEG_tempField BSEG_tempField} and {@link com.example.namespaces.odata06.link.BSEG_tempLink BSEG_tempLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.example.namespaces.odata06.BSEG_temp#BUKRS BUKRS}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG_temp#BELNR BELNR}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG_temp#GJAHR GJAHR}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG_temp#BUZEI BUZEI}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG_temp#KOART KOART}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG_temp#SHKZG SHKZG}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG_temp#DMBTR DMBTR}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG_temp#WRBTR WRBTR}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG_temp#PSWSL PSWSL}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG_temp#FDWBT FDWBT}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG_temp#FDTAG FDTAG}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG_temp#FKONT FKONT}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG_temp#HKONT HKONT}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG_temp#AWTYP AWTYP}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG_temp#AWKEY AWKEY}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG_temp#H_BUDAT H_BUDAT}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG_temp#H_BLDAT H_BLDAT}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG_temp#H_BLART H_BLART}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG_temp#H_HWAER H_HWAER}</li>
 * </ul>
 * 
 */
public interface BSEG_tempSelectable
    extends EntitySelectable<BSEG_temp>
{


}
