
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.21.0
 */

package com.example.namespaces.odata06.selectable;

import com.example.namespaces.odata06.BSEG;
import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;


/**
 * Interface to enable OData entity selectors for {@link com.example.namespaces.odata06.BSEG BSEG}. This interface is used by {@link com.example.namespaces.odata06.field.BSEGField BSEGField} and {@link com.example.namespaces.odata06.link.BSEGLink BSEGLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.example.namespaces.odata06.BSEG#BUKRS BUKRS}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG#BELNR BELNR}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG#GJAHR GJAHR}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG#BUZEI BUZEI}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG#BSCHL BSCHL}</li>
 * <li>{@link com.example.namespaces.odata06.BSEG#KOART KOART}</li>
 * </ul>
 * 
 */
public interface BSEGSelectable
    extends EntitySelectable<BSEG>
{


}
