
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.21.0
 */

package com.example.namespaces.odata06.selectable;

import com.example.namespaces.odata06.DummyHeader;
import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;


/**
 * Interface to enable OData entity selectors for {@link com.example.namespaces.odata06.DummyHeader DummyHeader}. This interface is used by {@link com.example.namespaces.odata06.field.DummyHeaderField DummyHeaderField} and {@link com.example.namespaces.odata06.link.DummyHeaderLink DummyHeaderLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.example.namespaces.odata06.DummyHeader#DUMMY_KEY DUMMY_KEY}</li>
 * <li>{@link com.example.namespaces.odata06.DummyHeader#TO_TBLBSEG TO_TBLBSEG}</li>
 * </ul>
 * 
 */
public interface DummyHeaderSelectable
    extends EntitySelectable<DummyHeader>
{


}
